/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 02:48:08 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.arrayQueue;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class arrayQueue_ESTest extends arrayQueue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      arrayQueue0.len = (-199);
      arrayQueue0.front = 1;
      arrayQueue0.display();
      assertFalse(arrayQueue0.isFull());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      assertEquals(0, arrayQueue0.getSize());
      
      arrayQueue0.len = (-199);
      arrayQueue0.display();
      assertTrue(arrayQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(2161);
      arrayQueue0.len = 2161;
      arrayQueue0.insert(184);
      assertEquals(2162, arrayQueue0.getSize());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      arrayQueue0.rear = (-919);
      // Undeclared exception!
      try { 
        arrayQueue0.insert(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -918
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      arrayQueue0.size = 920;
      assertTrue(arrayQueue0.isEmpty());
      
      arrayQueue0.front = 0;
      arrayQueue0.size = (-856);
      boolean boolean0 = arrayQueue0.isFull();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(3309);
      arrayQueue0.insert(3309);
      boolean boolean0 = arrayQueue0.isFull();
      assertEquals(1, arrayQueue0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(173);
      arrayQueue0.insert(1037);
      arrayQueue0.insert(173);
      arrayQueue0.remove();
      arrayQueue0.isFull();
      assertEquals(1, arrayQueue0.getSize());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      arrayQueue0.front = (-2613);
      // Undeclared exception!
      try { 
        arrayQueue0.peek();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2613
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1032);
      arrayQueue0.front = 301;
      int int0 = arrayQueue0.remove();
      assertEquals(-1, arrayQueue0.getSize());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      arrayQueue0.insert((-565));
      int int0 = arrayQueue0.remove();
      assertTrue(arrayQueue0.isEmpty());
      assertEquals((-565), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      assertTrue(arrayQueue0.isEmpty());
      
      arrayQueue0.front = 0;
      int[] intArray0 = new int[7];
      arrayQueue0.Queue = intArray0;
      arrayQueue0.peek();
      assertEquals(0, arrayQueue0.getSize());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(3309);
      arrayQueue0.insert(3309);
      int int0 = arrayQueue0.peek();
      assertEquals(1, arrayQueue0.getSize());
      assertEquals(3309, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      arrayQueue0.insert(1);
      int[] intArray0 = new int[2];
      intArray0[0] = (-919);
      arrayQueue0.Queue = intArray0;
      int int0 = arrayQueue0.peek();
      assertEquals(1, arrayQueue0.getSize());
      assertEquals((-919), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(3309);
      arrayQueue0.insert(3309);
      int int0 = arrayQueue0.getSize();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      arrayQueue0.len = (-199);
      int int0 = arrayQueue0.getSize();
      assertEquals((-199), int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      arrayQueue0.Queue = null;
      arrayQueue0.front = 0;
      // Undeclared exception!
      try { 
        arrayQueue0.remove();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      arrayQueue0.front = 0;
      // Undeclared exception!
      try { 
        arrayQueue0.remove();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      int[] intArray0 = new int[7];
      arrayQueue0.Queue = intArray0;
      arrayQueue0.Queue = null;
      arrayQueue0.front = 1;
      // Undeclared exception!
      try { 
        arrayQueue0.peek();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(706);
      arrayQueue0.Queue = null;
      // Undeclared exception!
      try { 
        arrayQueue0.insert(706);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      arrayQueue arrayQueue0 = null;
      try {
        arrayQueue0 = new arrayQueue((-2701));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(3309);
      arrayQueue0.insert(3309);
      arrayQueue0.isEmpty();
      assertEquals(1, arrayQueue0.getSize());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      int[] intArray0 = new int[6];
      arrayQueue0.Queue = intArray0;
      arrayQueue0.insert(0);
      arrayQueue0.rear = 2526;
      // Undeclared exception!
      try { 
        arrayQueue0.display();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 6
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(2157);
      arrayQueue0.display();
      assertEquals(0, arrayQueue0.getSize());
      assertTrue(arrayQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(3309);
      arrayQueue0.insert(3309);
      arrayQueue0.rear = (-1);
      assertEquals(1, arrayQueue0.getSize());
      
      int int0 = arrayQueue0.remove();
      assertEquals(3309, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(3309);
      // Undeclared exception!
      try { 
        arrayQueue0.remove();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Underflow Exception
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(2161);
      arrayQueue0.insert(184);
      arrayQueue0.insert(2161);
      arrayQueue0.Queue = null;
      // Undeclared exception!
      try { 
        arrayQueue0.display();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      arrayQueue0.rear = 0;
      arrayQueue0.insert((-3442));
      assertEquals(1, arrayQueue0.getSize());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      arrayQueue0.rear = 0;
      // Undeclared exception!
      try { 
        arrayQueue0.insert(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Overflow Exception
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1842);
      // Undeclared exception!
      try { 
        arrayQueue0.peek();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Underflow Exception
         //
         assertThrownBy("edu.osu.cs362.arrayQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      arrayQueue0.rear = 0;
      arrayQueue0.front = 0;
      boolean boolean0 = arrayQueue0.isFull();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      boolean boolean0 = arrayQueue0.isFull();
      assertEquals(0, arrayQueue0.getSize());
      assertTrue(arrayQueue0.isEmpty());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(1);
      boolean boolean0 = arrayQueue0.isEmpty();
      assertTrue(boolean0);
      assertEquals(0, arrayQueue0.getSize());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      arrayQueue arrayQueue0 = new arrayQueue(0);
      int int0 = arrayQueue0.getSize();
      assertTrue(arrayQueue0.isEmpty());
      assertEquals(0, int0);
  }
}
